apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kuberploy-local-dependencies
  labels:
    {{- include "kuberploy-local-dependencies.labels" . | nindent 4 }}
spec:
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values: [postgresql, valkey]
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/part-of: kuberploy
  egress: []
