apiVersion: v1
kind: ServiceAccount
metadata:
  name: kuberploy-postgresql
  labels:
    {{- include "kuberploy-local-dependencies.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kuberploy-valkey
  labels:
    {{- include "kuberploy-local-dependencies.labels" . | nindent 4 }}
    app.kubernetes.io/component: valkey
automountServiceAccountToken: false
