{{- if .Values.config.helmApplications.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.config.helmApplications.rendererNamespace }}
  labels:
    app.kubernetes.io/name: kuberploy
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: helm-renderer
    app.kubernetes.io/part-of: kuberploy
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
{{- end }}
