{{- range $component := list "api" "web" }}
{{- $config := index $.Values.components $component }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kuberploy.componentName" (dict "root" $ "component" $component) }}
  labels:
    {{- include "kuberploy.componentLabels" (dict "root" $ "component" $component) | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "kuberploy.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
  ports:
    - name: http
      port: {{ $config.port }}
      targetPort: http
{{- end }}
