{{- include "kuberploy-sealed-secrets.validate" . -}}
{{- if and .Values.secretFoundation.namespace.create .Values.secretFoundation.controller.managed }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- include "kuberploy-sealed-secrets.labels" . | nindent 4 }}
    kuberploy.io/sealed-secrets-namespace: "true"
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
{{- end }}
