{{- if .Values.monitoring.managed }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kuberploy-node-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kuberploy-monitoring.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
