{{- include "kuberploy-postgresql.validate" . -}}
{{- if and .Values.postgresqlFoundation.managed .Values.postgresqlFoundation.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- include "kuberploy-postgresql.labels" . | nindent 4 }}
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
{{- end }}
