{{- if .Values.postgresqlFoundation.managed }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kuberploy-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kuberploy-postgresql.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
