{{- include "kuberploy-runtime.validate" . -}}
{{- include "kuberploy-runtime.validateRuntime" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kuberploy-runtime.appName" . }}
  labels:
    {{- include "kuberploy-runtime.labels" . | nindent 4 }}
  annotations:
    kuberploy.io/application-id: {{ .Values.metadata.id | quote }}
automountServiceAccountToken: false
