{{- if and .Values.enabled (ne .Values.exposure.mode "internal") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kuberploy-registry.fullname" . }}
  labels:
    {{- include "kuberploy-registry.labels" . | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
    {{- if not (regexMatch "^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$" .Values.exposure.endpoint) }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.exposure.endpoint | quote }}
    {{- end }}
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: {{ .Values.exposure.ingressClassName }}
  tls:
    - {{- if not (regexMatch "^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$" .Values.exposure.endpoint) }}
      hosts:
        - {{ .Values.exposure.endpoint | quote }}
      {{- end }}
      secretName: {{ .Values.exposure.secretName }}
  rules:
    - {{- if not (regexMatch "^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$" .Values.exposure.endpoint) }}
      host: {{ .Values.exposure.endpoint | quote }}
      {{- end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "kuberploy-registry.fullname" . }}
                port:
                  name: registry
{{- end }}
