{{- if and .Values.enabled .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kuberploy-registry.fullname" . }}
  labels:
    {{- include "kuberploy-registry.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "kuberploy-registry.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        {{- range .Values.networkPolicy.allowedNamespaces }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . | quote }}
        {{- end }}
      ports:
        - port: {{ .Values.service.port }}
          protocol: TCP
  egress: []
{{- end }}
