apiVersion: v1
kind: Service
metadata:
  name: kuberploy-git
  labels:
    app.kubernetes.io/name: kuberploy-local-git
    app.kubernetes.io/instance: {{ .Release.Name }}
    kuberploy.io/test-run: {{ .Values.testRun | quote }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kuberploy-local-git
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: git
      port: 9418
      targetPort: git
      protocol: TCP
