apiVersion: v1
kind: ServiceAccount
metadata:
  name: kuberploy-git
  labels:
    app.kubernetes.io/name: kuberploy-local-git
    app.kubernetes.io/instance: {{ .Release.Name }}
    kuberploy.io/test-run: {{ required "global test-run label must be supplied with --set-string testRun=<run-id>" .Values.testRun | quote }}
automountServiceAccountToken: false
