apiVersion: v2
name: kuberploy-edge
description: Independently managed or adopted Traefik edge release for Kuberploy
type: application
version: 0.1.0-rc.374
appVersion: "0.1.0-rc.374"
kubeVersion: ">=1.34.0-0 <1.37.0-0"
annotations:
  kuberploy.io/traefik-chart-sha256: 42cf5c2a30a3630adb7cefa1ec5b84dfef0105599cd217c7574bd77c6ad369ee
dependencies:
  - name: traefik
    version: 41.1.1
    repository: https://traefik.github.io/charts
    condition: edge.traefik.managed
